scene: stadium

robot: JR2_Kinova
wheel_velocity: 0.100
arm_velocity: 0.4

task: reaching
fisheye: false

initial_pos: [0.0, 0.0, 0.0]
initial_orn: [0.0, 0.0, 0.0]

target_pos: [2.0, 0.0, 1.2]
target_orn: [0.0, 0.0, 0.0]

is_discrete: false
additional_states_dim: 33

reward_type: l2
success_reward: 10.0
slack_reward: -0.01
potential_reward_weight: 2.0
collision_reward_weight: -0.1
collision_ignore_link_a_ids: [2, 3, 5, 7]

discount_factor: 0.99

dist_tol: 0.05
max_step: 40

output: [sensor]
resolution: 256
fov: 1.57

use_filler: true
display_ui: false
show_diagnostics: false
ui_num: 2
ui_components: [RGB_FILLED, DEPTH]

speed:
  timestep: 0.001
  frameskip: 10

mode: web_ui
verbose:
fast_lq_render: true

visual_object_at_initial_target_pos: true
target_visual_object_visible_to_agent: true

debug: false